Add fingerprint to verifyFingerprint()
This is needed to fix: 
126: error: 'fingerprint' was not declared in this scope
   if (client.verify(fingerprint, host)) {
                     ^
exit status 1